// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Browser.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
protected:
  Fl_Double_Window *w;
  Fl_Input *titleInput;
  Fl_Input *idInput;
  Fl_Input *labelInput;
  Fl_Button *btnTitle;
  Fl_Browser *browser;
  Fl_Button *btnAdd;
  Fl_Button *btnDelete;
  Fl_Button *btnLoad;
  Fl_Button *btnStore;
};
#endif
