// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "window.h"

Fl_Double_Window* UserInterface::make_window() {
  { w = new Fl_Double_Window(477, 431);
    w->user_data((void*)(this));
    { titleInput = new Fl_Input(125, 10, 255, 20, "Title:");
    } // Fl_Input* titleInput
    { idInput = new Fl_Input(60, 85, 230, 20, "ID:");
    } // Fl_Input* idInput
    { labelInput = new Fl_Input(60, 110, 230, 20, "Label:");
    } // Fl_Input* labelInput
    { btnTitle = new Fl_Button(205, 40, 95, 25, "Set Title");
    } // Fl_Button* btnTitle
    { browser = new Fl_Browser(40, 185, 395, 215);
    } // Fl_Browser* browser
    { btnAdd = new Fl_Button(40, 145, 85, 25, "Add");
      btnAdd->shortcut(0xff0d);
    } // Fl_Button* btnAdd
    { btnDelete = new Fl_Button(140, 145, 85, 25, "Delete");
    } // Fl_Button* btnDelete
    { btnLoad = new Fl_Button(240, 145, 85, 25, "Load");
    } // Fl_Button* btnLoad
    { btnStore = new Fl_Button(345, 145, 85, 25, "Store");
    } // Fl_Button* btnStore
    w->end();
  } // Fl_Double_Window* w
  return w;
}
