// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "window.h"

MainFrame::MainFrame() {
  { w = new Fl_Double_Window(370, 420, "Random Selector");
    w->user_data((void*)(this));
    { btnSet = new Fl_Button(30, 150, 80, 30, "Set");
    } // Fl_Button* btnSet
    { boxResult = new Fl_Box(115, 290, 135, 80, "Winner");
      boxResult->box(FL_GTK_DOWN_BOX);
      boxResult->align(Fl_Align(257));
    } // Fl_Box* boxResult
    { btnPick = new Fl_Button(130, 220, 105, 35, "Pick");
    } // Fl_Button* btnPick
    { valueInput = new Fl_Int_Input(215, 150, 110, 30, "Quantity:");
      valueInput->type(2);
    } // Fl_Int_Input* valueInput
    w->size_range(200, 250, 400, 450);
    w->end();
  } // Fl_Double_Window* w
}
