// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Int_Input.H>

class MainFrame {
public:
  MainFrame();
  Fl_Double_Window *w;
  Fl_Button *btnSet;
  Fl_Box *boxResult;
  Fl_Button *btnPick;
  Fl_Int_Input *valueInput;
};
#endif
